[package]
name = "rsncp"
version = "0.0.0"
authors = ["Jeff Parent <jeff@commentedcode.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
